sudo: false
language: node_js
matrix:
  allow_failures:
  - node_js: stable
addon:
  firefox: latest
node_js:
- stable
- 6
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_script:
  - sleep 5
notifications:
  email: false
